[tool.poetry]
name = "rime"
authors = ["Edward Byers <byers@iiasa.ac.at>",
			"Mia Werning <werning@iiasa.ac.at>"]
description = "Rapid Impact Model Emulator"
repository = "https://github.com/iiasa/rime"
homepage = "https://iiasa.ac.at/programs/ece"
documentation = "https://github.com/iiasa/rime"
version = "0.1.0"
license = "GNU CPL v3"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
alive-progress = "^3.1.5"
dask = "^2024.2.0"
numpy = "^1.23"
pandas = "^2.2.0"
pyam-iamc = "^1.7"
xarray = "^2024.1.1"
scipy = "^1.12.0"
holoviews = "^1.18.3"
matplotlib = "^3.8.3"
seaborn = "^0.13.2"
rich = "^13.7.0"
pyyaml = "^6.0.1"
hvplot = "^0.9.2"
distributed = "^2024.2.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-multiversion = "^0.2.4"
sphinx-rtd-theme = "^2.0.0"
sphinxcontrib-bibtex = "^2.6.2"
sphinxcontrib-openapi = "^0.8.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
