[isimip]
simulation_round = "ISIMIP3b"
download_folder = "/mnt/PROVIDE/isimip"
climate_impact_explorer = "/mnt/PROVIDE/climate_impact_explorer/isimip3"
historical_year_min = 1980
variables = [ "tas", "pr", "tasmax", "tasmin", "sfcwind", "hurs", "huss", "ps", "prsn", "rlds", "rsds"]

[isimip.ISIMIP3b]
models = [ "CanESM5", "CNRM-CM6-1", "CNRM-ESM2-1", "EC-Earth3", "MIROC6", "GFDL-ESM4", "IPSL-CM6A-LR", "MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL",]
experiments = [ "historical", "ssp119", "ssp126", "ssp245", "ssp370", "ssp460", "ssp585",]

[isimip.ISIMIP2b]
models = ["IPSL-CM5A-LR", "GFDL-ESM2M", "MIROC5", "HadGEM2-ES"]
experiments = [ "historical", "rcp26", "rcp60", "rcp85",]

[preprocessing.regional]
weights = [ "latWeight", "gdp2005", "pop2005",]
masks_folder = "/mnt/PROVIDE/climate_impact_explorer/data/masks"

[preprocessing.seasons]
annual = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,]
winter = [ 12, 1, 2,]
spring = [ 3, 4, 5,]
summer = [ 6, 7, 8,]
autumn = [ 9, 10, 11,]

[emulator]
projection_baseline = [ 1995, 2014,]
projection_baseline_offset = 0.85
warming_level_min = 1
warming_level_step = 0.1
matching_method = "time"
running_mean_window = 21
temperature_sigma_first_year = 2015
temperature_sigma_range = 2.6
temperature_bin_size = 0.1
gmt_interannual_variability_sd = 0.14
isimip_binned_backend = [ "csv",]
quantiles = [ 0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99,]