[isimip]
simulation_round = ["ISIMIP3b"]
download_folder = "/mnt/ISIMIP"
climate_impact_explorer = "/mnt/PROVIDE/climate_impact_explorer"
historical_year_min = 1980
variables = [ "tas", "pr", "tasmax", "tasmin", "sfcwind", "hurs", "huss", "ps", "prsn", "rlds", "rsds"]

[isimip.ISIMIP3b]
models = [ "CanESM5", "CESM2-WACCM", "GFDL-ESM4", "CNRM-CM6-1", "CNRM-ESM2-1", "EC-Earth3", "KACE-1-0-G",
            "IPSL-CM6A-LR", "IITM-ESM", "MIROC6", "MPI-ESM1-2-HR", "MRI-ESM2-0", "TaiESM1", "UKESM1-0-LL",]
# experiments = [ "historical", "ssp119", "ssp126", "ssp245", "ssp370", "ssp460",  "ssp534-over", "ssp585",]
experiments = [ "historical", "ssp126", "ssp245", "ssp370", "ssp460", "ssp585",]

[isimip.ISIMIP2b]
models = ["IPSL-CM5A-LR", "GFDL-ESM2M", "MIROC5", "HadGEM2-ES"]
experiments = [ "historical", "rcp26", "rcp45", "rcp60", "rcp85",]

[indicators]
folder="/mnt/ISIMIP/indicators"

[indicator.maize_yield]
frequency = "annual"
spatial_aggregation = ["latWeight"]

[indicator.maize_yield.isimip_meta]
specifiers = ["variable", "crop"]
variable = "yieldchange"
crop = "mai"
ensemble_specifiers = ["model"] # further specifiers to identify the ensemble member

[indicator.rice_yield]
frequency = "annual"
spatial_aggregation = ["latWeight"]

[indicator.rice_yield.isimip_meta]
specifiers = ["variable", "crop"]
variable = "yieldchange"
crop = "ric"
ensemble_specifiers = ["model"] # further specifiers to identify the ensemble member

[indicator.wheat_yield]
frequency = "annual"
spatial_aggregation = ["latWeight"]

[indicator.wheat_yield.isimip_meta]
specifiers = ["variable", "crop"]
variable = "yieldchange"
crop = "whe"
ensemble_specifiers = ["model"] # further specifiers to identify the ensemble member

[indicator.soy_yield]
frequency = "annual"
spatial_aggregation = ["latWeight"]

[indicator.soy_yield.isimip_meta]
specifiers = ["variable", "crop"]
variable = "yieldchange"
crop = "soy"
ensemble_specifiers = ["model"] # further specifiers to identify the ensemble member

[indicator.river_discharge]
frequency = "monthly"
spatial_aggregation = ["latWeight", "pop2015"]
transform = "baseline_change_percent"

[indicator.river_discharge.isimip_meta]
specifiers = ["variable", "time_step", "soc_scenario", "sens_scenario"]
variable = "dis"
time_step = "monthly"
soc_scenario = "2015soc-from-histsoc"
sens_scenario = "default"
ensemble_specifiers = ["model"] # further specifiers to identify the ensemble member

[indicator.runoff]
frequency = "monthly"
spatial_aggregation = ["latWeight", "pop2015"]
transform = "baseline_change_percent"

[indicator.runoff.isimip_meta]
specifiers = ["variable", "time_step", "soc_scenario", "sens_scenario"]
variable = "qtot"
time_step = "monthly"
soc_scenario = "2015soc-from-histsoc"
sens_scenario = "default"
ensemble_specifiers = ["model"] # further specifiers to identify the ensemble member

[indicator.tas]
transform = "baseline_change"
units = "°C"
# monstat = ["mean"]

[indicator.tasmin]
transform = "baseline_change"
units = "°C"
# monstats = ["mean", "min"]

[indicator.tasmax]
transform = "baseline_change"
units = "°C"
# monstats = ["mean", "max"]

[indicator.pr]
transform = "baseline_change_percent"
# monstats = ["mean", "max", "max5day"]

[indicator.rx5day]
depends_on = ["pr"]
frequency = "annual"
custom = "rimeX.indicators:rx5day"
transform = "baseline_change_percent"
projection_baseline = [1995, 2014] # this also apply to ISIMIP2b
units = "mm"

[indicator.wet_bulb_temperature]
depends_on = ["tasmax", "hurs"]
expr = "(tasmax-273.15)*atan(0.151977*(hurs+8.313659)^0.5) + atan((tasmax-273.15)+hurs) - atan(hurs-1.676331) + 0.00391838*hurs^1.5*atan(0.023101*hurs) - 4.686035"
comment = """
Method: empirical formula for a pressure 101.325 kPa
source: https://journals.ametsoc.org/view/journals/apme/50/11/jamc-d-11-0143.1.xml
"""
transform = "baseline_change"
spatial_aggregation = ["latWeight", "pop2015"]
units = "°C"
title = "Wet Bulb Temperature"

[indicator.daily_temperature_variability]
depends_on = ["tas"]
depends_on_climatology = true
frequency = "annual"
custom = "rimeX.indicators:daily_temperature_variability"
transform = "baseline_change_percent"
units = "°C"

[indicator.number_of_wet_days]
depends_on = ["pr"]
frequency = "annual"
custom = "rimeX.indicators:number_of_wet_days"
transform = "baseline_change_percent"

[indicator.extreme_daily_rainfall]
depends_on = ["pr"]
depends_on_climatology = true
climatology_quantile = 0.999
frequency = "annual"
custom = "rimeX.indicators:extreme_daily_rainfall"
transform = "baseline_change_percent"
units = "mm"

[indicator.wet_bulb_temperature_q95]
_copy = "wet_bulb_temperature"
time_aggregation = "max"
running_window_statistic = "gev"  # gev or empirical or *mean*
running_window_quantile = 0.95


[preprocessing]
warming_level_step = 0.1  # used for pre-processing (input files for emulator)
warming_level_min = 1
running_mean_window = 21
isimip_binned_backend = [ "csv", ]
projection_baseline = [ 1995, 2014,] # this is used in rime-preproc-digitize
quantilemap_quantile_bins = 21

[preprocessing.regional]
weights = [ "latWeight", "gdp2015", "pop2015",]
masks_folder = "/mnt/PROVIDE/climate_impact_explorer/data/masks"
# isimip_binned_backend = [ "csv", "feather", "parquet"]

[preprocessing.seasons]
annual = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,]
winter = [ 12, 1, 2,]
spring = [ 3, 4, 5,]
summer = [ 6, 7, 8,]
autumn = [ 9, 10, 11,]

[index]
ignore = [ "value", "unit", "units" ]
required = [ "warming_level" ]
# default = [ "model", "scenario", "variable", "region", "year", "warming_level", "quantile", "percentile", "sample" ]

[emulator]
projection_baseline = [ 1995, 2014,]
projection_baseline_offset = 0.85
warming_level_step = 0.01 # used by default in rime-run-timeseries when --interp-warming-level is set
quantiles = [ 0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99,]