simulation_round: ISIMIP2b
download_folder: /mnt/PROVIDE/isimip
climate_impact_explorer_orig: /mnt/PROVIDE/climate_impact_explorer/data
climate_impact_explorer: /mnt/PROVIDE/climate_impact_explorer/isimip2
# warming_level_folder: "results"
# warming_level_name: null


models:
- IPSL-CM5A-LR
- GFDL-ESM2M
- MIROC5
- HadGEM2-ES

experiments:
- historical
- rcp26
- rcp60
- rcp85

variables:
- tas
- pr
# - tasmax
# - tasmin
# - sfcwind
# - rsds
# - hurs
# - soilmoist
# - thawdepth

weights:
- latWeight
- gdp2005
- pop2005


historical_year_min: 1980


# Options to load GCM temperature (for matching)
# ----------------------------------------------
# Projection baseline, see: https://gitlab.com/PeterPeter/impact_data_explorer/-/issues/1#note_1764693887
projection_baseline: [1986, 2005]
projection_baseline_offset: 0.69
# projection_baseline: [1995, 2014]
# projection_baseline_offset: 0.85

# options to calculate warming levels
warming_level_min: 1
warming_level_step: 0.1

# matching method can be "time" or "temperature". 
# "time" method: only the central year is written down
# "temperature" method: all years are written down.
matching_method: time

# define what "climate" (used in both methods)
running_mean_window: 21

# Options specific to temperature method: 
# temperature_sigma_first_year: 2015   # drop years before this
temperature_sigma_first_year: 2006     # drop years before this
temperature_sigma_range: 2.6
temperature_bin_size: 0.1  # additional range from temperature bin (will be centered on target) => typically same as warming_level_step

# Option specific to "pure" temperature method
# https://www.researchgate.net/figure/Interannual-variability-expressed-as-the-standard-deviation-in-annual-mean-global-surface_fig3_23668862 => HadCRUT (Collins et al 2001)
gmt_interannual_variability_sd: 0.14
samples: 5000

seasons:
  annual : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  winter : [12, 1, 2]
  spring : [3, 4, 5]
  summer : [6, 7, 8]
  autumn : [9, 10, 11]


isimip_binned_backend:
- csv

quantiles: [0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
