# This workflow checks that the code conforms to the Black style
# See https://black.readthedocs.io/en/stable/github_actions.html for details

name: Black formatting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: psf/black@stable
        with:
          options: "--color"
