# This workflow installs the package and builds the docs
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build the docs

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:
  sphinx:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.8'

      fail-fast: false


    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} py${{ matrix.python-version }}
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and package for building the docs
      run: |
        python -m pip install --upgrade pip
        pip install --editable .[doc]

    - name: Build the docs
      run: make --directory=doc html
